
export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;


export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export type FETCH_ARTICLES = typeof FETCH_ARTICLES;

export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export type LOAD_ARTICLES = typeof LOAD_ARTICLES;

